name: Release
on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write  # needed for OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "1.8.2"

      - name: Install project (no venv)
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --all-extras

      - name: Build dist
        run: poetry build

      # Official PyPI publish action (handles OIDC)
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # To publish to TestPyPI first, add:
          # repository-url: https://test.pypi.org/legacy/
